optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 3000
  batch_size: 128
  save_model: true
  loss: pairwise
  test_step: 3
  reproducible: true
  seed: 256
  patience: 5

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20]
  batch_size: 1024

data:
  type: general_cf
  name: amazon

model:
  name: gmf
  embedding_size: 256

  # dataset-specific parameters here
  reg_weight: 1.0e-6
  # for amazon
  amazon:
    reg_weight: 1.0e-6
  # for yelp
  yelp:
    reg_weight: 1.0e-6
  # for steam
  steam:
    reg_weight: 1.0e-6