optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0
  load_model: lightgcn 
  mode: finetune # fix, all, finetune

train:
  epoch: 3000
  batch_size: 128 # 4096
  save_model: true
  loss: pairwise
  test_step: 1
  reproducible: true
  seed: 256
  patience: 5

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20]
  batch_size: 1024

data:
  type: general_cf
  name: amazon

model:
  name: lightgcn_vq
  # general parameters here
  keep_rate: 0.8
  embedding_size: 256 # 32
  # dataset-specific parameters here
  layer_num: 3
  reg_weight: 1.0e-6
  kd_weight: 1.0e-1
  kd_temperature: 0.2
  # for amazon
  amazon:
    layer_num: 3
    reg_weight: 1.0e-6 # 7
    kd_weight: 1.0e-1
    kd_temperature: 0.2
  # for yelp
  yelp:
    layer_num: 3
    reg_weight: 1.0e-6 # 7
    kd_weight: 1.0e-1
    kd_temperature: 0.2
  # for steam:
  steam:
    layer_num: 3
    reg_weight: 1.0e-6 # 8
    kd_weight: 1.0e-1
    kd_temperature: 0.1
